name: Hello World
author: John Doe
description: Some description
inputs:
  who-to-greet:
    description: 'Who to greet'
    required: true
    default: Joh
outputs:
  time:
    description: 'The greeting time'
runs:
  using: "docker"
  image: "Dockerfile"
  # entrypoint:
  args:
    - ${{ inputs.who-to-greet }}
